export const SET_SELECTED_CELL: "SET_SELECTED_CELL" = "SET_SELECTED_CELL";
export const SET_MAIN_VALUE: "SET_MAIN_VALUE" = "SET_MAIN_VALUE";
export const DELETE_MAIN_VALUE: "DELETE_MAIN_VALUE" = "DELETE_MAIN_VALUE";
export const SET_NOTES_VALUE:'SET_NOTES_VALUE'='SET_NOTES_VALUE';
export const DELETE_NOTES_VALUE: "DELETE_NOTES_VALUE" = "DELETE_NOTES_VALUE";
export const DELETE_ALL_NOTES_VALUES: "DELETE_ALL_NOTES_VALUES" = "DELETE_ALL_NOTES_VALUES";
export const GET_GAME_FIELD: "GET_GAME_FIELD" = "GET_GAME_FIELD";
export const TOGGLE_NOTES_MODE: "TOGGLE_NOTES_MODE" = "TOGGLE_NOTES_MODE";
