export const SET_SELECTED_CELL: "SET_SELECTED_CELL" = "SET_SELECTED_CELL";
export const SET_MAIN_VALUE_TO_CELL: "SET_MAIN_VALUE_TO_CELL" = "SET_MAIN_VALUE_TO_CELL";
export const GET_GAME_FIELD: "GET_GAME_FIELD" = "GET_GAME_FIELD";
